### PR TITLE
Implement docker into project

### PR DESCRIPTION
**Pull request by ss77995ss**
### Description
Run the application on docker environment
Follow the steps from `Getting Started`

### CODE REVIEW

**Comment by chunming-c** [comment]
Good! There are some suggestion for you.
First, you could list all these guideline in your `README`. Place them under the topic of `Getting started` seems pretty good. Also, `docker-compose down` aims to gracefully shut down your composed containers. You could give it a try.

**Comment by chunming-c** [comment]
It seems not a good idea to use `babel-node` for `production` mode. Please try to compile source first and serve your server instead. 

```js
npm install -d @babel-cli

./node_modules/.bin/babel src -d dist && node dist
```

ref: https://github.com/babel/example-node-server

**Comment by ss77995ss** [comment]
Thanks for the advice! I also remove some unused modules in `package.json` and I think it still required to use `babel-core@^7.0.0-bridge.0` although I am using `@babel/core` because Jest needs it to run unit tests.

ref: https://jestjs.io/docs/en/23.5/getting-started

**Review by chunming-c — APPROVED** [review]
LGTM 👍

**Pull request merged**
